# Generated by Django 4.2.4 on 2023-09-02 16:22

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    superuser = CustomUser(
        username='admin',
        password=make_password('Hola123...'),
        is_staff=True,
        is_superuser=True,
    )
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
