version: '3'

services:
  db:
     image: postgres:16rc1
     restart: on-failure
     volumes:
      - postgres_data:/var/lib/postgresql/data/
     environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: .
      dockerfile: ./local/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure:20
    command: ./local/entrypoint
 
volumes:
  postgres_data:

