# Generated by Django 4.2.4 on 2023-09-04 20:33

from django.db import migrations
from utils.read_initial_data import DataReader


def populate_curr_brokers(apps, schema_editor):
    Money = apps.get_model("position", "Money")
    Broker = apps.get_model("position", "Broker")
    # DataReader([
    #     {"file_path": "utils/initial_data/money.csv", "model": Money},
    #     {"file_path": "utils/initial_data/broker.csv", "model": Broker},
    # ]).run()


class Migration(migrations.Migration):
    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_curr_brokers),
    ]
