# Generated by Django 4.2.4 on 2023-09-10 15:46

from django.db import migrations
from utils.read_initial_data import DataReader
from utils.constant import DataCreator


def populate_database(apps, schema_editor):
    reader = DataReader(
        data_file="utils/initial_data/data_inversiones.ods",
        app="position",
        data_definition=[
            {
                "sheet_name": "money",
                "model": "Money",
                "related_fields": [],
            },
            {
                "sheet_name": "broker",
                "model": "Broker",
                "related_fields": [],
            },
            {
                "sheet_name": "account",
                "model": "Account",
                "related_fields": [
                    {"model": "Broker", "field": "broker"}
                ]
            },
            {
                "sheet_name": "assets",
                "model": "Asset",
                "related_fields": [
                    {"model": "Account", "field": "account"}
                ]
            },
            {
                "sheet_name": "positions",
                "model": "Position",
                "related_fields": [
                    {"model": "Position", "field": "reference"},
                    {"model": "Asset", "field": "asset"}
                ]
            }
        ]
    )
    reader.run(mode=DataCreator.POPULATE)
    reader.run(mode=DataCreator.FIXTURE)


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_database),
    ]
