# Generated by Django 4.2.4 on 2023-09-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_populate_curr_brokers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='broker',
        ),
        migrations.AddField(
            model_name='asset',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='position.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='long_swap_coeficient',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='short_swap_coeficient',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='swap_coeficient',
            field=models.CharField(blank=True, default='0000000', max_length=7, null=True),
        ),
    ]
