# Generated by Django 4.2.4 on 2023-09-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_remove_asset_broker_asset_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='order_type',
            field=models.SmallIntegerField(choices=[(1, 'Buy'), (0, 'Sell')]),
        ),
    ]
