# Generated by Django 4.2.4 on 2023-09-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_alter_position_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='leverage',
        ),
        migrations.AddField(
            model_name='position',
            name='is_leveraged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='position.position'),
        ),
    ]
