# Generated by Django 4.2.4 on 2023-09-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0005_remove_position_leverage_position_is_leveraged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='direction',
            field=models.SmallIntegerField(choices=[(1, 'In'), (0, 'Out')], default=1),
        ),
        migrations.AlterField(
            model_name='position',
            name='order_type',
            field=models.SmallIntegerField(choices=[(1, 'Long'), (0, 'Short')]),
        ),
    ]
