# Generated by Django 4.2.4 on 2023-09-09 19:12

from django.db import migrations, models
import utils.constant


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0007_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='direction',
            field=models.SmallIntegerField(choices=[(utils.constant.DirectionType['IN'], 'In'), (utils.constant.DirectionType['OUT'], 'Out')], default=utils.constant.DirectionType['IN']),
        ),
        migrations.AlterField(
            model_name='position',
            name='order_type',
            field=models.SmallIntegerField(choices=[(utils.constant.PositionsType['LONG'], 'Long'), (utils.constant.PositionsType['SHORT'], 'Short')]),
        ),
    ]
